<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.consler.librelauncher</groupId>
    <artifactId>librelauncher</artifactId>
    <version>2.0</version>
    <name>LibreLauncher</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <junit.version>5.12.1</junit.version>
        <javafx.version>25.0.4</javafx.version>
        <main.class>net.consler.librelauncher.Main</main.class>
    </properties>

    <repositories>
        <repository>
            <id>central</id>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
        <repository>
            <id>jitpack</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>dev.dirs</groupId>
            <artifactId>directories</artifactId>
            <version>26</version>
        </dependency>
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
            <version>3.7.2</version>
        </dependency>
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf-extras</artifactId>
            <version>3.7.2</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>com.google.code.gson</groupId>
            <artifactId>gson</artifactId>
            <version>2.14.0</version>
        </dependency>
        <dependency>
            <groupId>ca.weblite</groupId>
            <artifactId>webview</artifactId>
            <version>1.10.2</version>
        </dependency>
        <dependency>
            <groupId>net.consler</groupId>
            <artifactId>librelauncherlib</artifactId>
            <version>-0d11e3525a-1</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.13.0</version>
                <configuration>
                    <source>25</source>
                    <target>25</target>
                </configuration>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.5.2</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <shadedArtifactAttached>true</shadedArtifactAttached>
                            <shadedClassifierName>universal</shadedClassifierName>
                            <createDependencyReducedPom>false</createDependencyReducedPom>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>${main.class}</mainClass>
                                </transformer>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <!--APP-IMAGE-->
        <profile>
            <id>app-image</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <version>1.6.0</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals><goal>jpackage</goal></goals>
                                <configuration>
                                    <name>LibreLauncher</name>
                                    <appVersion>2.0</appVersion>
                                    <vendor>net.consler</vendor>
                                    <destination>${project.build.directory}/dist</destination>
                                    <mainJar>${project.build.finalName}-universal.jar</mainJar>
                                    <mainClass>${main.class}</mainClass>
                                    <type>APP_IMAGE</type>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!--WINDOWS EXE-->
        <profile>
            <id>exe</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <version>1.6.0</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals><goal>jpackage</goal></goals>
                                <configuration>
                                    <name>LibreLauncher</name>
                                    <appVersion>2.0</appVersion>
                                    <vendor>net.consler</vendor>
                                    <destination>${project.build.directory}/dist</destination>
                                    <mainJar>${project.build.finalName}-universal.jar</mainJar>
                                    <mainClass>${main.class}</mainClass>
                                    <type>EXE</type>
                                    <winDirChooser>true</winDirChooser>
                                    <winShortcut>true</winShortcut>
                                    <winMenu>true</winMenu>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!--WINDOWS MSI-->
        <profile>
            <id>msi</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <version>1.6.0</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals><goal>jpackage</goal></goals>
                                <configuration>
                                    <name>LibreLauncher</name>
                                    <appVersion>2.0</appVersion>
                                    <vendor>net.consler</vendor>
                                    <destination>${project.build.directory}/dist</destination>
                                    <mainJar>${project.build.finalName}-universal.jar</mainJar>
                                    <mainClass>${main.class}</mainClass>
                                    <type>MSI</type>
                                    <winDirChooser>true</winDirChooser>
                                    <winShortcut>true</winShortcut>
                                    <winMenu>true</winMenu>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!--MACOS DMG-->
        <profile>
            <id>dmg</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <version>1.6.0</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals><goal>jpackage</goal></goals>
                                <configuration>
                                    <name>LibreLauncher</name>
                                    <appVersion>2.0</appVersion>
                                    <vendor>net.consler</vendor>
                                    <destination>${project.build.directory}/dist</destination>
                                    <mainJar>${project.build.finalName}-universal.jar</mainJar>
                                    <mainClass>${main.class}</mainClass>
                                    <type>DMG</type>
                                    <macPackageName>LibreLauncher</macPackageName>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!--MACOS PKG-->
        <profile>
            <id>pkg</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <version>1.6.0</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals><goal>jpackage</goal></goals>
                                <configuration>
                                    <name>LibreLauncher</name>
                                    <appVersion>2.0</appVersion>
                                    <vendor>net.consler</vendor>
                                    <destination>${project.build.directory}/dist</destination>
                                    <mainJar>${project.build.finalName}-universal.jar</mainJar>
                                    <mainClass>${main.class}</mainClass>
                                    <type>PKG</type>
                                    <macPackageName>LibreLauncher</macPackageName>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!--LINUX DEB-->
        <profile>
            <id>deb</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <version>1.6.0</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals><goal>jpackage</goal></goals>
                                <configuration>
                                    <name>librelauncher</name>
                                    <appVersion>2.0</appVersion>
                                    <vendor>net.consler</vendor>
                                    <destination>${project.build.directory}/dist</destination>
                                    <mainJar>${project.build.finalName}-universal.jar</mainJar>
                                    <mainClass>${main.class}</mainClass>
                                    <type>DEB</type>
                                    <linuxShortcut>true</linuxShortcut>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>

        <!--LINUX RPM-->
        <profile>
            <id>rpm</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.panteleyev</groupId>
                        <artifactId>jpackage-maven-plugin</artifactId>
                        <version>1.6.0</version>
                        <executions>
                            <execution>
                                <phase>package</phase>
                                <goals><goal>jpackage</goal></goals>
                                <configuration>
                                    <name>librelauncher</name>
                                    <appVersion>2.0</appVersion>
                                    <vendor>net.consler</vendor>
                                    <destination>${project.build.directory}/dist</destination>
                                    <mainJar>${project.build.finalName}-universal.jar</mainJar>
                                    <mainClass>${main.class}</mainClass>
                                    <type>RPM</type>
                                    <linuxShortcut>true</linuxShortcut>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>